### ISSUE TITLE
CI: build for ESP8266 RTOS SDK v3.3

### ISSUE THREAD

**Issue by UncleRus** [UncleRus/esp-idf-lib#170]
Currently only master branch is building, but v3.3 is latest stable version, so I beleive it needs to be supported in CI.

**Comment by trombik** [comment]
the problem of ESP8266 RTOS SDK is, the release management is poor. they just tags random points of the commit history. the stable release is not stable at all, at the least, it has been so. for example, they updated the tool-chain in this release without mentioning it in the release note. I often need to patch the tree locally. issues are never taken care of. the master branch is hit-and-miss, sometimes particular bugs you are facing are fixed in master. the documentation is out of sync. the project is developed in a very different culture from `esp-idf`.

let me see if it's possible.
