### ISSUE TITLE
I want to push there BME280 driver, but idk how

### ISSUE THREAD

**Issue by martinius96** [UncleRus/esp-idf-lib#215]
Hello there,
I have edited original Bosch Sensortec driver for BME280 (BMP280 is available in your projects).
**And I would like to upload it there but I don't know how, I am not good with branches etc...**
Upload is not working to this repository.

ESP-IDF project with example for BME280 is available there: https://github.com/martinius96/bme280-ESP-IDF-driver
Ready for being used. There is also readme where user can read how to use example.
User can change I2C address, MASTER SDA / SCL pins, frequency of I2C bus and also operation mode.

**Can someone please merge it there from my repo?**
Thanks a lot, Martin

**Comment by UncleRus** [comment]
I will not accept your contribution for a variety of reasons:
1. Bosch source code license is unacceptable in this repository.
2. The source code of the driver is not designed as a separate component, but depends on the program code in main.c
3. The source code does not use `i2cdev` when working with the I2C bus.
4. The source code does not follow rules.
5. Instead of a well-formed pull request, I see an issue with the request to do it for you.
etc, etc, etc.

Please study the source codes of the components existing here and rules for contributing: 
https://github.com/UncleRus/esp-idf-lib/blob/master/CONTRIBUTING.md
