### ISSUE TITLE
CI: Sync with ESP-IDF

### ISSUE THREAD

**Issue by UncleRus** [UncleRus/esp-idf-lib#401]
### The issue

We need to update the CI build scripts because:

- ESP-IDF now uses new toolchain version for the `master` branch.
- ESP-IDF v4.4.3 released

### Confirmation

- [X] This report is not a bug report in code, a question, nor a request for drivers.

**Comment by trombik** [comment]
> ESP-IDF now uses new toolchain version for the master branch.

true, but the toolchains in the CI environments are also updated automatically. otherwise, the build would have failed. this is because `Run idf_tools.py install` step installs the toolchains.

this means `Download toolchain if it does not exist` step and other steps are no longer necessary. I will fix it later when the new CI is proved to be stable.

**Comment by trombik** [comment]
> true, but the toolchains in the CI environments are also updated automatically. otherwise, the build would have failed. this is because `Run idf_tools.py install` step installs the toolchains.

well, `make` build needs `ccache` setup and path to `gcc`. just fixed it.
